from .hitbox import set_hitbox_monster
from .default import DefaultMonster

from .frog import Frog
from .zombie import Zombie
from .dark_knight import DarkKnight
from .cyclops import Cyclops
from .jack_lantern import JackLantern
from .minion import Minion
from .fire_ball import FireBall
from .daemon import Daemon
from .ghost import Ghost
from .necromancer import Necromancer
from .undead import Undead
from .harpy import Harpy
from .vines import Vines
from .brambles import Brambles
from .ent import Ent
from .piranha import Piranha
from .tentacle import Tentacle
from .base_tentacles import BaseTentacles
from .vortex import Vortex
from .kraken import Kraken
from .garou import Garou
from .villager import Villager
from .alchemist import Alchemist
from .fly import Fly
from .witch import Witch
from .vampire import Vampire
from .devourer import Devourer
from .pestilence import Pestilence
from .pestilence_medium import PestilenceMedium
from .enyo import Enyo
from .deino import Deino
from .pemphredo_ghost import PemphredoGhost
from .pemphredo import Pemphredo
from .graeae import Graeae
from .lamb import Lamb
from .gargamel import Gargamel

tab = [Zombie, Cyclops, JackLantern, Necromancer, Harpy, Ent, Villager, Alchemist, Witch, Vampire]
