from .default import DefaultWeapon
from .submachine_gun_up import SubmachineGunUp
from .submachine_gun import SubmachineGun
from .crossbow_up import CrossbowUp
from .crossbow import Crossbow
from .devil_blade import DevilBlade
from .dragon_head import DragonHead
from .magic_wand import MagicWand
from .shadow_daggers import ShadowDaggers
